### ISSUE TITLE
gitignore is needed

### ISSUE THREAD

**Issue by tkizm1** [POJOa/ScheduleArrangement#1]
![image](https://cloud.githubusercontent.com/assets/5886048/25771605/dd2223ac-3288-11e7-9b69-cf8f114a4e0a.png)

Edit Add topics ....

hhhh

**Comment by escapar** [comment]
I don't know which to ignore , I mean every single lovely file ,  they're doing very very fascinating jobs #FilesLiveMatter

**Comment by tkizm1** [comment]
*.iml
.mvn
.idea

**Comment by escapar** [comment]
话说回来 大佬是怎么保证这些文件被删掉之后到另一个开发环境 IDE还是保持原来的布局的...

**Comment by tkizm1** [comment]
rm -rf .idea/ *.iml lib 
然后坐等idea自动导入就可以了

**Comment by tkizm1** [comment]
![image](https://cloud.githubusercontent.com/assets/5886048/25798996/e962f4f0-3415-11e7-8e4f-d730e5176887.png)

**Comment by tkizm1** [comment]
![image](https://cloud.githubusercontent.com/assets/5886048/25799791/0d422e6a-3419-11e7-9075-4da15471cc66.png)
![image](https://cloud.githubusercontent.com/assets/5886048/25799810/2046ac7a-3419-11e7-8dd7-69a97e87e943.png)
![image](https://cloud.githubusercontent.com/assets/5886048/25799852/4da298c8-3419-11e7-9091-eecb3b10f808.png)

**Comment by escapar** [comment]
挺6的 3Q!
